# Generated by Django 3.1.4 on 2021-02-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_categories_comments_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.URLField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
