# Generated by Django 3.1.4 on 2021-03-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
