# Generated by Django 3.1.4 on 2021-03-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='posting_time',
            field=models.CharField(max_length=64),
        ),
    ]
