# Generated by Django 3.1.4 on 2021-03-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listings_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='winner',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
